config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'carts/index'

devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  # devise_for :admins
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  get "/users/show" => "users#show",as: :users
  delete "/users/destroy" =>"users#destroy"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy]
  resources :carts
  resources :histroies
  resources :history_addresses
  resources :categories,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :brands,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :sizes,only: [:new, :create, :index, :update, :edit, :destroy]

  get "/admin_users/edit/:id" => "admin_users#edit", as: :edit_adminusers_to_users
  post "/admin_users/:id" => "admin_users#update", as: :adminusers_to_users
  root "items#index"
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	has_many :histories
	has_many :carts
	belongs_to :category

	enum active: { display: 0, hide: 1}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user

    # 履歴表示
    @histories_for_user = History.where(user_id:@user.id)
    @histories = History.where(user_id: @user.id).order("id desc") #ログインユーザーの履歴を一覧化
    @history_ids = @histories.pluck(:history_address_id).uniq #@historiesからhistory_address_idの一覧を取得して配列にする

    # 上記をベースにビュー側で行っている事まとめ
    #   変数
    #     histories 該当ユーザーの全履歴明細
    #     histroies_ids 該当ユーザーがこれまで使用した全配送住所（history_address_id）
    #     h_histories 同一配送先住所(history_address_id)ごとにまとめた履歴
    #     h_h_item 同一配送先住所（history_address_id)内のひとつひとつの履歴
    @price = 540
    @total_price = 0 #合計金額初期化
  end

  def destroy
    @user = current_user
    @user.active = 1#activeカラムを1（削除済）にして、保存
    @user.email = "#{@user.last_sign_in_at.to_i.to_s}_#{@user.email.to_s}"
    if @user.save
      flash[:notice] = "ユーザーを削除しました。"
      signed_out = Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    end
    redirect_to root_path#リダイレクト先の変更（deviseの初期値　User#index から rootへ変更
  end
end

app/views/users/show.html.erb
   <%if flash%>
   　<!-- ログイン時のメッセージ格納 -->
      <% flash.each do |i,msg|%>
       <div class="<%= "flash_#{i}"%> flash">
         <%= msg %><br>
       </div>
      <% end %>
   <% end %>

<div class="user-box clearfix">
  <i class="fa fa-user-circle" aria-hidden="true"><p class="title1">ユーザー情報</p></i><br>
<!-- ユーザー情報の一覧 -->
  <div class="user-text">
    <span class="user_logo">カナ</span> 　<%= "#{@user.kana_lastname} #{@user.kana_firstname}" %><br>
    <span class="user_logo">名前</span> 　<%= "#{@user.lastname} #{@user.firstname}" %><br>
    <span class="user_logo">メールアドレス</span> 　<%= @user.email %><br>
    <span class="user_logo">郵便番号</span> 　<%= @user.postal_code %><br>
    <span class="user_logo">住所</span> 　<%= @user.address %><br>
    <span class="user_logo">建物名</span> 　<%= @user.address_more %><br>
    <span class="user_logo">電話番号</span> 　<%= @user.phone %>-<%= @user.phone2 %>-<%= @user.phone3 %><br>
<!-- プロフィール編集&削除ボタン -->
    <%= link_to "退会する", users_destroy_path,method: :delete ,class: "square_btn2",data: { :confirm => "退会しますか？\n退会すると戻せませんのでご注意ください。"}%>
    <%= link_to "編集", edit_user_registration_path ,class: "square_btn1"%>
  </div>
</div>


<!-- 購入履歴情報 -->
<div class="user-box"><i class="fa fa-history" aria-hidden="true"><p class="title1">購入履歴</p></i>

  <div class="history-text">

    <% if @history_ids.presence == nil %>
          <p>購入履歴はありません</p>
    <% else %>

        <% @history_ids.each do |i| %> <!-- コントローラーでhistory_address_idを抽出して@history_idsへ配列で格納 -->
          <% h_histories = @histories.where(history_address_id: i) #history_addressで抽出した履歴一覧%>
          <% h_history_first = h_histories.first #住所、日時表示のため、うち一番上のレコードを抽出%>
          <% h_histries_count = 0 %>
          <% h_histories.each {|h_h_item| h_histries_count += h_h_item.count} %>
          <!-- 一回の買い物情報分を抽出して出力 -->

                <p>購入日：<%= h_history_first.created_at.strftime('%Y/%m/%d %H:%M')  %>　<span class="<%= "#{h_history_first.order_status}_style"%> order_status_style"><%= h_history_first.order_status_i18n%></span></p>
                  <div class="address-text">
                    【送付先情報】<br>
                    <p><%= h_history_first.history_address.postal_code%> <%= h_history_first.history_address.address %> <%= h_history_first.history_address.address_more %></p>
                      名前 : <%= h_history_first.history_address.lastname%>  <%= h_history_first.history_address.firstname%>   (電話番号 : <%= h_history_first.history_address.phone%>-<%= h_history_first.history_address.phone2 %>-<%= h_history_first.history_address.phone3 %>) <br>
                  </div>

                  購入商品：<%= h_histories.size %>（購入点数：<%= h_histries_count %> ）<br>
                  <table class="history_table">
                    <thead>
                      <tr>
                        <th class="history_items_name">アルバム</th>
                        <th class="history_items_name">アーティスト</th>
                        <th>値段</th>
                        <th>数</th>
                        <th>小計</th>
                      </tr>
                    </thead>

                    <% h_histories.each do |h_h_item| #history_addressで抽出した履歴一覧から個別出力%>
                    <!-- 個別の商品情報を繰り返し出力 -->
                      <tr>
                        <td><%= h_h_item.item.item_name %></td>
                        <td><%= h_h_item.item.artist_name %></td>
                        <td><%= number_to_currency(h_h_item.price, unit: "¥", precision:0) %></td>
                        <td> ×<%= h_h_item.count%> =</td>
                        <td><%= number_to_currency(h_h_item.price * h_h_item.count, unit: "¥", precision:0) %></td>
                      </tr>
                      <% @total_price += h_h_item.price * h_h_item.count %>
                    <% end %>

                    <!-- 合計金額を出すためのテーブルの合計行 -->
                    <tr class="history_address_line">
                      <% if @total_price <= 3000 %>
                      <td colspan="3"></td>
                      <td>送料：</td>
                      <td>￥<%= @price %></td>
                    </tr>
                    <tr>
                      <td colspan="3"></td>
                      <td>合計：</td>
                      <td><%= number_to_currency(@total_price+@price, unit: "¥", precision:0) %></td>
                    </tr>
                    <% else %>
                    <td colspan="3"></td>
                    <td>送料：</td>
                    <td>無料</td>
                    <tr>
                      <td colspan="3"></td>
                      <td>合計：</td>
                      <td><%= number_to_currency(@total_price, unit: "¥", precision:0) %></td>
                    </tr>
                    <% end %>
                  </table>
                    <% @total_price = 0 #total_price初期化%>
                    <br><br><hr><br>
        <% end #繰り返し処理の終了%>
      <% end #条件分岐の終了（履歴がない場合）%>
    </div>
  </div>