config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'carts/index'

devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  # devise_for :admins
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  get "/users/show" => "users#show",as: :users
  delete "/users/destroy" =>"users#destroy"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy]
  resources :carts
  resources :histroies
  resources :history_addresses
  resources :categories,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :brands,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :sizes,only: [:new, :create, :index, :update, :edit, :destroy]

  get "/admin_users/edit/:id" => "admin_users#edit", as: :edit_adminusers_to_users
  post "/admin_users/:id" => "admin_users#update", as: :adminusers_to_users
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :items
end

app/models/disc.rb
class Disc < ApplicationRecord
	  belongs_to :item
	  has_many :songs, dependent: :delete_all
	  accepts_nested_attributes_for :songs
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/history_address.rb
class HistoryAddress < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	has_many :histories
	has_many :carts
	belongs_to :category

	enum active: { display: 0, hide: 1}

end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def index #カート内の書品一覧
		@carts = Cart.all
		@fee = 360 #送料
		@total_price = 0
		@carts.each do |cart|
	      if current_user.id == cart.user_id
	         @total_price += cart.item.price*cart.count
	      end
    	end
	end

	def create
		@cart = Cart.new(cart_params)
		@cart.user_id = current_user.id
		if Cart.find_by(item_id: @cart.item_id,user_id:current_user.id)
       		redirect_to carts_path, flash: {n: "選んだ商品は既にカートに入っています。ご確認ください。"}
    	else
			@cart.save
			redirect_to carts_path
		end
	end

	def update
		@cart = Cart.find(params[:id])
		@cart.update(cart_params)
		redirect_to carts_path
	end

	def destroy
		@cart = Cart.find(params[:id])
		@cart.delete
		redirect_to carts_path
	end


	private

	def cart_params
		params.require(:cart).permit(:user_id,:item_id,:count)
	end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/carts/index.html.erb
   <%if flash%>
   　<!-- ログイン時のメッセージ格納 -->
      <% flash.each do |i,msg|%>
       <div class="<%= "flash_#{i}"%> flash">
         <%= msg %><br>
       </div>
      <% end %>
      <p class="cart-top title"><i class="fa fa-shopping-cart fa_icon"></i><%= "#{current_user.lastname} #{current_user.firstname}" %>


  <% if @carts.where(user_id:current_user.id).presence == nil %>
    <p>カートには何も入っていません。</p>

  <% else %>
      <% @carts.each do |cart| %>
        <% if current_user.id == cart.user_id %>
                <div class="item-image">
                  <%= attachment_image_tag cart.item, :image, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %>
                </div><!--商品画像-->

                <div class="album-text">
                  <p class="title"><%= cart.item.item_name %></p>
                  <span class="item-logo">サイズ </span>
                  <span class="item-logo"></span>

                  <div>
                    <span><%= number_to_currency(cart.item.price, unit: "¥", precision:0) %></span>
                    <% if cart.item.stock == 0 %>
                      <span>(売り切れ)</span>
                    <% else %>
                      <span>(在庫<%= cart.item.stock %>個)</span>
                    <% end %>
                    <% if cart.item.active != "display"%>
                      <p style="color:red">この商品は現在、販売停止中です。</p>
                    <% end %>
                    <%= form_for(cart, url: cart_path(cart.id), html: {method: 'PUT'}) do |f| %><!--商品の個数を変更するフォーム-->
                      <%= f.number_field :count ,min:0,max: cart.item.stock %>
                      <%= f.hidden_field :user_id, :value => current_user.id %>
                      <%= f.hidden_field :item_id, :value => cart.item.id %>
                      <%= f.submit "個数を変更" %>
                      <button><%= link_to "　削除　", cart_path(cart.id), method: :delete %></button><br><!--商品削除ボタン-->
                    <% end %>
                <!-- １商品の合計金額 -->
                    小計: <%= number_to_currency(cart.item.price*cart.count, unit: "¥", precision:0) %><br>
                  </div>
              </div>
         <% end %>
  <% end %>
</div>
  <div class="total-price-box">
     <% if @total_price <= 3000 %>
        <p>送料：￥<%= @price %></p>
        カート内合計金額：<br>
     <% else %>
        <p>送料：無料</p>
        カート内合計金額：<%= number_to_currency(@total_price, unit: "¥", precision:0) %><br>
     <% end %>
      <!-- カートの合計金額 -->
  </div>
  <% end %>
    <!-- 送り先情報 -->
  <div class="price-box1 clearfix">
    <div class="adress-box-left">
        <p class="title"><i class="fa fa-bus"></i> 配送先情報</p>

      <%= form_for :history_address,url:history_addresses_path do |f|%>

              <span><span class="ad-form-label">姓（カタカナ）</span><%= f.text_field :kana_lastname,placeholder: "ヤマダ",class:"form_style_half form_input",value:"#{current_user.kana_lastname}" %></span>
              <span><span class="ad-form-label">名（カタカナ)</span><%= f.text_field :kana_firstname,placeholder: "タロウ",class:"form_style_half form_input",value:"#{current_user.kana_firstname}" %></span><br>
              <span><span class="ad-form-label">姓</span><%= f.text_field :lastname,placeholder: "山田" ,class:"form_style_half form_input",value:"#{current_user.lastname}" %></span>
              <span><span class="ad-form-label">名</span><%= f.text_field :firstname,placeholder: "太郎",class:"form_style_half form_input",value:"#{current_user.firstname}" %></span><br>
              <span><span class="ad-form-label">郵便番号</span><%= f.text_field :postal_code,placeholder: "111-0000",class:"form_style_half form_input",value:"#{current_user.postal_code}" %></span><br>
              <span><span class="ad-form-label">住所</span><%= f.text_field :address,placeholder: "東京都渋谷区渋谷１−１−１",class:"form_style form_input",value:"#{current_user.address}" %></span><br>
              <span><span class="ad-form-label">住所(建物名)</span><%= f.text_field :address_more ,placeholder: "マンション",class:"form_style form_input",value:"#{current_user.address_more}" %></span><br>
              <span><span class="ad-form-label">電話番号</span><%= f.text_field :phone,placeholder: "090",class:"form_style2 form_input",value:"#{current_user.phone}"%>-<%= f.text_field :phone2,placeholder: "0000",class:"form_style2 form_input",value:"#{current_user.phone2}"%>-<%= f.text_field :phone3,placeholder: "0000",class:"form_style2 form_input",value:"#{current_user.phone3}"%></span>
              <span class="history-address-form"><%= f.submit "購入", :disable_with => '購入中...' ,class:"square_btn3",data: { confirm: "本当に購入しますか?" }%></span>

      <% end %>
      <% end %>
   <br><br>
  </div>
</div>