config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'carts/index'

devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
      }
  # devise_for :admins
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.
  get "/users/show" => "users#show",as: :users
  delete "/users/destroy" =>"users#destroy"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy]
  resources :carts
  resources :histroies
  resources :history_addresses
  resources :categories,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :brands,only: [:new, :create, :index, :update, :edit, :destroy]
  resources :sizes,only: [:new, :create, :index, :update, :edit, :destroy]

  get "/admin_users/edit/:id" => "admin_users#edit", as: :edit_adminusers_to_users
  post "/admin_users/:id" => "admin_users#update", as: :adminusers_to_users
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :items
end

app/models/disc.rb
class Disc < ApplicationRecord
	  belongs_to :item
	  has_many :songs, dependent: :delete_all
	  accepts_nested_attributes_for :songs
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/history_address.rb
class HistoryAddress < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	has_many :histories
	has_many :carts
	belongs_to :category

	enum active: { display: 0, hide: 1}

end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @item = Item.where(active: 0)
    @q = @item.search(params[:q])
    @items = @q.result(distinct: true)

    #非表示アイテムを表示しない
    @no_item = Item.where(active: 1)
    @no_q = @no_item.search(params[:q])
    @no_items = @no_q.result(distinct: true)
  end


  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)
    #Rails.logger.info(@item)
    @item.save
    # Rails.logger.info(@item)
    redirect_to ("/items")
  end

  def show
    @item = Item.find(params[:id])
    @cart = Cart.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      #updateが完了したら一覧ページへリダイレクト
      redirect_to ("/items")
    else
      #updateを失敗すると編集ページへ
      render ("items/edit")
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.delete
    redirect_to("/items")
  end

  private
    def item_params
        params.require(:item).permit(:item_name, :image, :price,:item_season, :stock, :color_id, :category_id, :brand_id, :size_id, :release_date)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/items/_form.html.erb
<div class="row">
  <h2>商品登録</h2>
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @item.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  　<div class="col-sm-12">
      商品画像　　　　<%= f.attachment_field :image %>
    </div>
  <div class="row">
    <div class="col-sm-12">
      商品名　　　　　<%= f.text_field :item_name, class:"form-control", rows:"3" %>
    </div>
  </div>

      ブランド　　　　<%= f.collection_select :brand_id, Brand.all, :id, :brand_name %><%=link_to("ブランド名編集",brands_path)%><br>

  <!--カテゴリー登録-->
      カテゴリー　　　<%= f.collection_select :category_id, Category.all, :id, :name %><%=link_to("カテゴリー編集",categories_path)%>
   <div class="row">
    <div class="col-sm-12">
      価格　　　　　　<%= f.text_field :price, class:"form-control", rows:"3" %>
    </div>
  </div>

      サイズ　　　　　<%= f.collection_select :size_id, Size.all, :id, :size_name %><%=link_to("サイズ編集",sizes_path)%><br>
   <div class="row">
    <div class="col-sm-12">
      在庫数　　　　　<%= f.text_field :stock, class:"form-control", rows:"3" %>
    </div>
  </div>
     <div class="row">
    <div class="col-sm-12">
      発売日　　　　　<%= f.date_field :release_date, class:"form-control", rows:"3" %>
    </div>
  </div>


  <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
  <%= link_to"一覧に戻る", "/" %>
</div>
<% end %>

app/views/items/edit.html.erb
<h1>edit</h1>
<%= render 'form', item: @item %>

app/views/items/index.html.erb
<%if flash%>
   　<!-- ログイン時のメッセージ格納 -->
      <% flash.each do |key,msg|%>
       <div class="flash_<%= key%> flash">
         <%= msg %><br>
       </div>
      <% end %>
   <% end %>

<h1>商品一覧</h1>
<% if admin_signed_in? %>
	<%=link_to("カテゴリー編集",categories_path)%>
<% end %>

	<div class="item_container">
		<% if params[:q].present? && params[:q][:artist_name_or_label_name_or_item_name_cont].present? %>
		<div>
			<p>検索語句：　<%= params[:q][:artist_name_or_label_name_or_item_name_cont] %></p>
		</div>
		<% end %>
		<table class="item_index_box">

			<% @items.each do |item| %>
			<tr>
				<td>
					<!--画像画面左　登録がない場合noimageを表示-->
					<%= link_to item_path(item.id) do %>
					<%= attachment_image_tag item, :image, :fill, 150, 150, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %>
					<% end %>
				</td>
					<!--商品内容-->
				<td class="item_index_box_detail">
					<p><%= item.item_name %></p>
					<p><h3><%= link_to "#{item.item_name}", item_path(item) %></h3></p>
					<p></p>
					<p><%= number_to_currency(item.price, :unit => "¥", :precision => 0) %>
					<% if item.stock == 0 %>
                      <span>売り切れ</span>
                    <% else %>
                      <span>(在庫: <%= item.stock %>個)</span>
                    <% end %>
					</p>
					<td>
						<% if admin_signed_in? %>
							<%=link_to("編集する","/items/#{item.id}/edit")%><br>
						<% end %>
					</td>
				</td>
			</tr>
			<% end %>


		</table>
	</div>
	<% if admin_signed_in? %>
	<h1>非表示商品一覧</h1>
	<div class="item_container">
		<% if params[:q].present? && params[:q][:artist_name_or_label_name_or_item_name_cont].present? %>
		<div>
			<p>検索語句：　<%= params[:q][:artist_name_or_label_name_or_item_name_cont] %></p>
		</div>
		<% end %>

		<table class="item_index_box">
			<% @no_items.each do |item| %>
			<tr>
				<td>
					<!--画像画面左　登録がない場合noimageを表示-->
					<%= link_to item_path(item.id) do %>
					<%= attachment_image_tag item, :image, :fill, 150, 150, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %>
					<% end %>
				</td>
					<!--商品内容-->
				<td class="item_index_box_detail">
					<p><%= item.artist_name %></p>
					<p><h3><%= link_to "#{item.item_name}", item_path(item) %></h3></p>
					<p><%= item.label_name %></p>
					<p><%= number_to_currency(item.price, :unit => "¥", :precision => 0) %>
					<% if item.stock == 0 %>
                      <span>売り切れ</span>
                    <% else %>
                      <span>(在庫: <%= item.stock %>個)</span>
                    <% end %>
					</p>
					<td>
						<% if admin_signed_in? %>
							<%=link_to("編集する","/items/#{item.id}/edit")%><br>
						<% end %>
					</td>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
	<% end %>

app/views/items/new.html.erb
<%= render 'form', item: @item %>

app/views/items/show.html.erb
<div class="item-box">
　<!--　商品画像  -->
  <div class="item-image-box">
    <%= attachment_image_tag @item, :image, format: 'jpeg', class:"album-image" %>
  </div>
	<!--　商品情報　 -->
	<div class="album-text">
	<p class="title"><%= @item.item_name %></p>
	<span class="item-logo">サイズ　 </span>  <span class="item-logo"></span><br><br>
  発売日：　<%= @item.release_date %><br>
	価格：　<%= number_to_currency(@item.price, :unit => "¥", :precision => 0) %><br>
	在庫：　<% if @item.stock == 0 %>
          <span>売り切れ</span>

        <% elsif user_signed_in? %>
          <span>残り<%= @item.stock %>個</span>
          <!-- 数量フォーム -->
          <%= form_for @cart do |f| %>
            <%= f.number_field :count ,min:1,max:@item.stock, value:"1" %>
            <%= f.hidden_field :item_id, :value => @item.id %>
          <%= f.submit "カートに入れる" ,class:"square_btn1"%>
          <% end %>
        <% elsif admin_signed_in? %>
          <span>残り<%= @item.stock %>個</span><br>
          <%= link_to '変更', edit_item_path(@item), class:"square_btn2" %>

         <% else %>
          <span>残り<%= @item.stock %>個</span>
         <% end %>
 </div>
</div>